# Generated by Django 5.1.4 on 2025-01-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home',
        ),
    ]
